{{- if and (.Values.job.enabled) (not (empty .Values.job.cronSchedule)) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "srpt-svc.name" . }}-job
  labels:
    {{- include "srpt-svc.labels" . | nindent 4 }}
    env: {{ .Values.tier }}
    service: {{ include "srpt-svc.name" . }}
    version: {{ .Chart.Version }}
  {{- if not (empty .Values.additionalAnnotations) }}
  annotations:
    {{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy | default "Forbid" }}
  failedJobsHistoryLimit: 1
  schedule: {{ .Values.job.cronSchedule | quote }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 1
      template:
        metadata:
          name: {{ include "srpt-svc.name" . }}-job
          labels:
            env: {{ .Values.tier }}
            service: {{ include "srpt-svc.name" . }}
            version: {{ .Chart.Version }}
        spec:
          serviceAccountName: {{ include "srpt-svc.serviceAccountName" . }}
          containers:
            - name: main
              image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
            {{- if .Values.env }}
              env:
              {{- range .Values.env }}
              - name: {{ .name }}
                {{- if .value }}
                value: {{ .value | quote }}
                {{- else if .valueFrom }}
                valueFrom:
                  secretKeyRef:
                    key: {{ .valueFrom.secretKeyRef.key }}
                    name: {{ .valueFrom.secretKeyRef.name }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- if or (.Values.volumes.secrets) (not (empty .Values.config)) }}
              volumeMounts:
              {{- if .Values.volumes.secrets }}
                {{- range .Values.volumes.secrets }}
                - name: {{ print .name "-vol" }}
                  mountPath: {{ .mountPath }}
                  readOnly: true
                {{- end }}
              {{- end }}
              {{- if not (empty .Values.config) }}
                - name: config
                  mountPath: {{ .Values.configPath | default "/data/config" }}
              {{- end }}
            {{- end }}
            {{- if gt (len .Values.job.args) 0 }}
              {{- if .Values.job.command }}
              command: {{ .Values.job.command }}
              {{- end }}
              args:
                {{- range .Values.job.args }}
                - {{ . }}
                {{- end }}
            {{- end }}
              imagePullPolicy: {{ .Values.job.image.pullPolicy }}
            {{- if .Values.resources }}
              resources: {{ toYaml .Values.resources | nindent 16 }}
            {{- end }}
        {{- if or (.Values.volumes.secrets) (not (empty .Values.config)) }}
          volumes:
          {{- if .Values.volumes.secrets }}
          {{- range .Values.volumes.secrets }}
          - name: {{ print .name "-vol" }}
            secret:
              secretName: {{ .name }}
          {{- end }}
          {{- end }}
          {{- if not (empty .Values.config) }}
          - name: config
            configMap:
              name: {{ include "srpt-svc.name" . }}
          {{- end }}
        {{- end }}
          restartPolicy: Never
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}